#!/bin/sh
set -e

FIRMWARE_DIR="/lib/firmware/rtw88"

if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" ]; then
    for FILE in "$FIRMWARE_DIR"/*.disabled; do
        ORIGINAL_FILE="${FILE%.disabled}"
        dpkg-divert --remove --rename "$ORIGINAL_FILE"
    done
fi

#DEBHELPER#
