#!/bin/bash
set -e

FILES=(
    #DIVERSIONS#
)

if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" ]; then
    for FILE in "${FILES[@]}"; do
        dpkg-divert --remove --rename "$FILE"
    done
fi

#DEBHELPER#
